[package]
name = "rustscraper"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "*"
reqwest = {version = "*", features = ["blocking"]}
scraper = "*"
tokio = {version = "*", features = ["full"]}

[[bin]]
name = "get_html"
path = "src/get_html.rs"