[package]
name = "rustscraper"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "*"
reqwest = {version = "*", features = ["blocking"]}
scraper = "*"
tokio = {version = "*", features = ["full"]}
thirtyfour = "*"
selenium-rs = "0.1.2"

[[bin]]
name = "parse_gsheet"
path = "src/parse_gsheet.rs"